def build_pr_description(plan, task_memory, build_logs):
    work_item_id = plan["id"]
    title = plan["title"]

    # Categorise subtasks
    implemented = []
    tests = []
    other = []

    for entry in task_memory.entries:
        task_title = entry["task"]
        subtask_title = entry["subtask"]

        lower = f"{task_title} {subtask_title}".lower()

        if "test" in lower:
            tests.append(subtask_title)
        elif "refactor" in lower or "finalise" in lower:
            other.append(subtask_title)
        else:
            implemented.append(subtask_title)

    # Build PR body
    lines = []

    lines.append(f"## Work Item {work_item_id}: {title}")
    lines.append("")
    lines.append("### Summary")
    lines.append(f"This PR implements the backend changes required for **{title}**.")
    lines.append("")

    lines.append("### Plan Summary")
    for t in plan["tasks"]:
        lines.append(f"- {t['title']}")
    lines.append("")

    if implemented:
        lines.append("### Implemented")
        for item in implemented:
            lines.append(f"- {item}")
        lines.append("")

    if tests:
        lines.append("### Tests Added")
        for item in tests:
            lines.append(f"- {item}")
        lines.append("")

    if other:
        lines.append("### Additional Work")
        for item in other:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("### Build & Test Status")
    lines.append(build_logs)
    lines.append("")

    lines.append("### Notes")
    lines.append("- This PR was generated by the automated SDLC orchestrator.")
    lines.append("- File contents and internal execution details have been omitted for clarity.")
    lines.append("")

    return "\n".join(lines)
